spring:
  profiles:
    active: local
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: root
    password: root
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true

logging:
  level:
    liquibase: DEBUG

stripe:
  api-key: ${STRIPE_KEY}
  webhook-secret: ${STRIPE_KEY_WH}