spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true

logging:
  level:
    liquibase: DEBUG

stripe:
  api-key: ${STRIPE_KEY}
  webhook-secret: ${STRIPE_KEY_WH}