// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU93a36R-j-YSAbBSvgDlCslGsQVXh7IE',
    appId: '1:899365890717:android:1c253ce451354054fd0274',
    messagingSenderId: '899365890717',
    projectId: 'modulegym',
    storageBucket: 'modulegym.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8HUSta0mrOXljAcwOK0R1AjNqIPSo8x8',
    appId: '1:899365890717:ios:56a6033912cf22d4fd0274',
    messagingSenderId: '899365890717',
    projectId: 'modulegym',
    storageBucket: 'modulegym.firebasestorage.app',
    iosClientId: '899365890717-qn5m8qt3m70b2t5ivccp7dkq4k43o36n.apps.googleusercontent.com',
    iosBundleId: 'com.yevhen.moduleGym',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf3xVaRxMY3-kqgiWP6JTqpLlzUeRiunc',
    appId: '1:899365890717:web:44b4da87b59419bdfd0274',
    messagingSenderId: '899365890717',
    projectId: 'modulegym',
    authDomain: 'modulegym.firebaseapp.com',
    storageBucket: 'modulegym.firebasestorage.app',
    measurementId: 'G-F5N61K7BLV',
  );

}